# These are supported funding model platforms
# GitHub will display a "Sponsor" button in the repository sidebar

# Open Collective
open_collective: vizualni-admin

# GitHub Sponsors (GitHub maintains a list of these)
github: [acailic]
#### donta anny here as i didnt created them
